[package]
name = "zap-rs"
version = "0.1.0"
edition = "2018"
authors = ["kprotty"]

[features]
default = []
nightly = []
all = ["runtime", "sync"]

os = []
core = []
sync = []
runtime = ["core", "os"]
