[package]
name = "benches"
version = "0.0.0"
edition = "2018"
authors = ["kprotty"]

[dependencies]
tokio = { version = "0.3", features = ["rt", "rt-multi-thread", "sync", "macros"] }

[[bin]]
name = "spawn"
path = "./spawn.rs"

[[bin]]
name = "yield"
path = "./yield.rs"