name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1
    - uses: kprotty/setup-zig@v1.1.0
      with:
        version: master
    - run: zig build test
